version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.19.3"
replacements:
  group: "dev.tr7zw"
  name: "NotEnoughAnimations"
  id: "notenoughanimations"
  version: "1.6.3"
  author: "tr7zw"
  relocationpackage: "dev.tr7zw.notenoughanimations"
  dependencies: ""
  licensename: "LICENSE"
  modrinthid: MPCX6s5C
  curseforgeid: 433760
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
rootProject:
  template: "."
subProjects:
  NEAFabric:
    template: "Fabric"
  NEAForge:
    template: "Forge"